version: '3.8'
services:
  application:
      build: .
      container_name : flask_app
      ports:
        - '5000:5000'
      volumes:
        - .:/app 
      depends_on:
        - db

  db:
    build: ./database/
    restart: always
    environment:
      MYSQL_DATABASE: police_station_db
      MYSQL_ROOT_PASSWORD: T00thless:p
    ports:
      - '4306:3306' 
